before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NZhdos9bs5xeRoU9jMUu56hhRV0tqJWc2rxtwlJH7puPIY/rrteOzBjDuEwk4918WsB3+wfyKTCGh4Say/h/W45wxho+Sgqqj9z3LQv8+wur5dmB84WgXGeBg9rb4vX+f6l1361gpUU2lDpBMiKNtVsMqKhQJQjQYwcN6L7ktKTg2crmIKEW2FtzMQJmKAJQ5v+p2JHyThs4UF7lqr5LrLwMR03X/E63I3TtFmmQLembvstbVyA/FboP+KniziyX4VDmah58eT6OEqlgrZaj2YZ0uzu/1vQzDeiOqZ+3i4UO+FGPqREsBxD6M99LTccK0by/NYMdDHPkfhCvYZ/oak0JOhQWSHkfx3aLlWJOpVKjK1TPm0EtvRGm4/TfV5RpTah3lcyEw17I325NWf3sl35JiHWXg8u48Pf8cO9vxQdkgCH/sbU0f3FLvcJP9HBiCtBJjfWTIZkQA6TvKI5zyY8U7i+VQbktudgpA6Hqq7SFauHYCa/S4xHWf9eqdYkMMopKQXHEQ7RDU6cYkj/H4Mjno5V2N0ykqPyVvS9AMXs9BZs5QLyuKPQL/ko2yNSTd8YdqqoSE3IJCZmtxDz7k8p4tk4cQ5ZA2FUjE2YlWmFKbPtBqGCjWCFv6k3kqw0yg+RrNxCsbOECYgCYH17MCnJjr48wrbSBtyiKquXY3Ls= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
